"""Hit/miss expected-belief mixture in the CasADi EFE planner.

Two jobs here.

1. **Non-regression anchor.** ``R_plan`` precision-blending is FROZEN method for
   the published single-camera paper: ``honest_campaign_v1`` must stay
   reproducible bit-for-bit. ``test_flag_off_is_bit_identical_to_golden`` replays
   a fixed set of ``(u, m0, S0, goal, progress)`` points through the real
   ``make_efe_valgrad_fn`` with ``use_hit_miss_mixture=False`` and asserts exact
   float equality (``==``, not ``approx``) against values captured from the
   pre-change code. The golden literals below were generated by running this
   file's own harness against the unmodified ``casadi_efe.py``, so any drift in
   the frozen path fails here.

2. **Mixture semantics.** The mixture replaces "launder availability into R" with
   an honest two-branch expectation over a Bernoulli availability variable:
   with probability ``p_use`` a measurement arrives and the belief takes a full
   Kalman update with the *conditional* covariance ``R_cond``; with probability
   ``1 - p_use`` nothing arrives and the belief is unchanged. Tests pin the two
   endpoints, monotonicity in ``p_use``, and PSD-ness throughout.

All beliefs/fields here are synthetic test fixtures, not measurements.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

ca = pytest.importorskip("casadi")

from planning.core import casadi_efe as cefe  # noqa: E402


# --------------------------------------------------------------------------
# Shared fixtures (deterministic; no file or artifact dependencies)
# --------------------------------------------------------------------------

def _camera_H() -> np.ndarray:
    """A concrete oblique-camera homography, so the golden numbers are realistic."""
    from unav_common.camera_model import ObliqueCameraModel

    cam = ObliqueCameraModel(
        cam_pos=(-5.0, -5.5, 4.8),
        look_at=(1.5, 1.5, 0.0),
        img_width=1280,
        img_height=720,
        fov_h_rad=1.2,
    )
    return np.asarray(cam.H, dtype=float)


def _p_vis_fixture():
    """Synthetic smooth availability field (a test fixture, not a fitted GP)."""
    s = ca.MX.sym("s", 3)
    val = 1.0 / (1.0 + ca.exp(-(1.2 * s[0] - 0.8 * s[1] + 0.5)))
    return ca.Function("p_vis_fixture", [s], [val], ["state"], ["p"])


def _nogo_belief_fixture():
    """Synthetic belief-aware no-go penalty (exercises the S_drive path)."""
    m = ca.MX.sym("m", 3)
    S = ca.MX.sym("S", 3, 3)
    val = ca.exp(-(m[0] ** 2 + m[1] ** 2)) * (1.0 + ca.trace(S))
    return ca.Function("nogo_belief_fixture", [m, S], [val], ["m", "S"], ["c"])


def _params(**overrides) -> cefe.CasadiEfeParams:
    base = dict(
        R_visible=np.diag([2.5 ** 2, 2.5 ** 2]),
        R_miss=np.diag([120.0 ** 2, 120.0 ** 2]),
        control_weight=0.05,
        risk_scale=1.25,
        ambiguity_scale=1.0,
        discount_gamma=0.98,
        process_noise_xy=0.05,
        process_noise_theta=0.03,
        visibility_sigma_kappa=1.0,
        goal_prior_u_std_start=80.0,
        goal_prior_v_std_start=80.0,
        goal_prior_u_std_final=18.0,
        goal_prior_v_std_final=18.0,
        goal_tightening_power=0.45,
        goal_progress_n_steps=90,
        use_belief_nogo_cost=False,
        time_horizon=6,
        dt=0.4,
        Du=2,
    )
    base.update(overrides)
    return cefe.CasadiEfeParams(**base)


# Fixed evaluation points: (u_flat, m0, S0, goal_obs, goal_xy, progress_index0).
_EVAL_POINTS = (
    (
        [0.30, 0.10, 0.35, -0.05, 0.40, 0.00, 0.25, 0.15, 0.30, -0.20, 0.20, 0.05],
        [-1.50, 0.75, 0.35],
        [[0.040, 0.006, 0.001], [0.006, 0.055, -0.002], [0.001, -0.002, 0.020]],
        [640.0, 380.0],
        [2.0, 1.0],
        12.0,
    ),
    (
        [-0.20, 0.40, 0.10, 0.30, 0.45, -0.25, 0.05, 0.35, -0.15, 0.20, 0.50, -0.10],
        [2.25, -1.40, -0.90],
        [[0.180, -0.030, 0.004], [-0.030, 0.110, 0.007], [0.004, 0.007, 0.060]],
        [300.0, 520.0],
        [-1.0, 2.5],
        45.0,
    ),
    (
        [0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00, 0.50, 0.00],
        [0.10, 0.10, 1.57],
        [[0.010, 0.000, 0.000], [0.000, 0.010, 0.000], [0.000, 0.000, 0.005]],
        [900.0, 200.0],
        [3.5, -2.0],
        80.0,
    ),
)


def _golden_cases():
    """The (name, params, kwargs) configurations replayed by the golden test."""
    return (
        ("et1_vis", _params(), dict(approx="ET1", p_vis_state=_p_vis_fixture())),
        ("et2_vis", _params(), dict(approx="ET2", p_vis_state=_p_vis_fixture())),
        (
            "et1_vis_beliefnogo",
            _params(use_belief_nogo_cost=True),
            dict(
                approx="ET1",
                p_vis_state=_p_vis_fixture(),
                nogo_belief_cost=_nogo_belief_fixture(),
            ),
        ),
        ("et1_novis", _params(), dict(approx="ET1")),
    )


def _evaluate_case(params, kwargs):
    """Return [(objective, gradient_list), ...] over ``_EVAL_POINTS``."""
    valgrad = cefe.make_efe_valgrad_fn(params, _camera_H(), **kwargs)
    out = []
    for u, m0, S0, goal_obs, goal_xy, prog in _EVAL_POINTS:
        val, grad = valgrad(
            np.asarray(u, dtype=float),
            np.asarray(m0, dtype=float),
            np.asarray(S0, dtype=float),
            np.asarray(goal_obs, dtype=float),
            np.asarray(goal_xy, dtype=float),
            float(prog),
        )
        out.append((float(val), [float(g) for g in np.asarray(grad).reshape(-1)]))
    return out


# --------------------------------------------------------------------------
# Golden values captured from the PRE-CHANGE casadi_efe.py.
# Regenerate ONLY with an explicit decision to move frozen method:
#   python3 experiments/efe_hit_miss_mixture/regenerate_golden.py
# --------------------------------------------------------------------------
GOLDEN: dict[str, list[tuple[str, list[str]]]] = {
    'et1_vis': [
        ('0x1.aa18dff31be14p+3', [
            '-0x1.5c919cdd9d20dp+1',
            '0x1.8ea8c20a8b50bp-1',
            '-0x1.0ffcfa177dc0cp+1',
            '0x1.f8e83eaeb1249p-2',
            '-0x1.aeae915edcf6cp+0',
            '0x1.f381bfcce9c55p-3',
            '-0x1.3c8968796d872p+0',
            '0x1.0a8fe6298297ep-3',
            '-0x1.83720a4dd9302p-1',
            '0x1.b4bd19d653e5ap-6',
            '-0x1.9c88b3a7b8aa6p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.3541f08ca13bap+8', [
            '0x1.424e50d9f0d76p+5',
            '-0x1.16afc43875671p+1',
            '0x1.0b9c96eafb60ap+5',
            '-0x1.ed00b7d83702bp+0',
            '0x1.a50489656bab0p+4',
            '-0x1.a920e00dc565fp-2',
            '0x1.472a7e83a807ep+4',
            '-0x1.446ba129ee4bbp-2',
            '0x1.a671dcbbc8116p+3',
            '-0x1.386046c2e6f19p-1',
            '0x1.a0662b148e886p+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1e4b09c436370p+8', [
            '0x1.1729f5983265cp+4',
            '0x1.808b414c87c80p+4',
            '0x1.df9b72b0da663p+3',
            '0x1.006824f81d3c8p+4',
            '0x1.89f387d467468p+3',
            '0x1.33aa31f34dd91p+3',
            '0x1.2e53041fa0e35p+3',
            '0x1.3390793aa5535p+2',
            '0x1.9b3e4cae89332p+2',
            '0x1.99d930eb17790p+0',
            '0x1.a2b1d91fa1b69p+1',
            '0x0.0p+0',
        ]),
    ],
    'et2_vis': [
        ('0x1.aaca43b2505f3p+3', [
            '-0x1.5d4a051430233p+1',
            '0x1.8df59373a2142p-1',
            '-0x1.1099b18a92086p+1',
            '0x1.f800a08eebc7cp-2',
            '-0x1.afa3898e31be6p+0',
            '0x1.f29845fd1f9cdp-3',
            '-0x1.3d3fbf47bbae0p+0',
            '0x1.0a1806626c042p-3',
            '-0x1.846ba3151436fp-1',
            '0x1.b3c1e3bd3bf27p-6',
            '-0x1.9d7459d289397p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.35544546b2372p+8', [
            '0x1.430f5da87366ap+5',
            '-0x1.178c1cea0e299p+1',
            '0x1.0c51657059336p+5',
            '-0x1.ee05708e2d2f3p+0',
            '0x1.a64b5139d1320p+4',
            '-0x1.ac4d4bf2bd580p-2',
            '0x1.48240eb3c65ffp+4',
            '-0x1.45d202829895ap-2',
            '0x1.a7d5163c1c84ap+3',
            '-0x1.3858300fa1860p-1',
            '0x1.a22b82d4366dfp+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1e5b2b91dd294p+8', [
            '0x1.1772329607737p+4',
            '0x1.80a9bc1932d84p+4',
            '0x1.e0337eeaaf9c2p+3',
            '0x1.007e9f4548a6bp+4',
            '0x1.8a8620d28577cp+3',
            '0x1.33c7d72e5f094p+3',
            '0x1.2ed35cecc5b18p+3',
            '0x1.33b0df3a927d2p+2',
            '0x1.9c0176979dbc0p+2',
            '0x1.9a082a009d3ccp+0',
            '0x1.a38c7a9e9e6cdp+1',
            '0x0.0p+0',
        ]),
    ],
    'et1_vis_beliefnogo': [
        ('0x1.ae75b722ebcb6p+3', [
            '-0x1.5374559d2fa91p+1',
            '0x1.7485b590f266ep-1',
            '-0x1.08fc0b8908df6p+1',
            '0x1.d62da8400c271p-2',
            '-0x1.a336d98c35d0fp+0',
            '0x1.cffee5096bed8p-3',
            '-0x1.344fc7a83060cp+0',
            '0x1.ef699bc157ed6p-4',
            '-0x1.7af449882d7dap-1',
            '0x1.8f029b3ddf33ap-6',
            '-0x1.925a214493ccdp-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.35421e0e570c2p+8', [
            '0x1.424b75a1d9328p+5',
            '-0x1.16b03c9627e2bp+1',
            '0x1.0b9a9f5a08e2dp+5',
            '-0x1.ed012db3172a3p+0',
            '0x1.a5023939dd990p+4',
            '-0x1.a920f1eb4f95dp-2',
            '0x1.4728de1a4e9ccp+4',
            '-0x1.446b597d527e6p-2',
            '0x1.a66fbf1dcb00fp+3',
            '-0x1.386030df5d9d1p-1',
            '0x1.a0651b3786ca9p+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1ed729f946307p+8', [
            '0x1.12c355d685f7dp+4',
            '0x1.80c6b3ed376b3p+4',
            '0x1.d80819435e7e9p+3',
            '0x1.008a03b0e8667p+4',
            '0x1.8415c7cdbe3aap+3',
            '0x1.33cc5c13570e0p+3',
            '0x1.2a4de3335fb5bp+3',
            '0x1.33acd498f5975p+2',
            '0x1.96953c71d1b24p+2',
            '0x1.99f854629a4b4p+0',
            '0x1.9ecd7b20b2a69p+1',
            '0x0.0p+0',
        ]),
    ],
    'et1_novis': [
        ('0x1.73621bfb0d965p+3', [
            '-0x1.392dfa9f58d94p+1',
            '0x1.51426b6d19b2cp-1',
            '-0x1.e942aa44608a8p+0',
            '0x1.ab356de3a02c2p-2',
            '-0x1.827d13dd1967cp+0',
            '0x1.a7b2243ce905cp-3',
            '-0x1.1bfbce19cd35bp+0',
            '0x1.c6cbedd403baep-4',
            '-0x1.5c7b678470450p-1',
            '0x1.6a7f2c8c70fd2p-6',
            '-0x1.717e0890b1fe0p-2',
            '0x1.9f2409f0a6e2dp-11',
        ]),
        ('0x1.353e60fefbbfcp+8', [
            '0x1.425dd8cb46b37p+5',
            '-0x1.16addf6fa28bbp+1',
            '0x1.0ba9301dd00acp+5',
            '-0x1.ecff5861cf5cfp+0',
            '0x1.a5176181762e8p+4',
            '-0x1.a922b46cd8b5dp-2',
            '0x1.47382ae692d95p+4',
            '-0x1.446fa604b734fp-2',
            '0x1.a683cdd9693ddp+3',
            '-0x1.386262b804cb3p-1',
            '0x1.a0756067f0b24p+2',
            '-0x1.9f2409f0a6e2dp-10',
        ]),
        ('0x1.1d962d70598dcp+8', [
            '0x1.149dd97cf00b5p+4',
            '0x1.7e804d1f832d7p+4',
            '0x1.db3cbbcb27db6p+3',
            '0x1.fe0aded6d57c2p+3',
            '0x1.865be23387eebp+3',
            '0x1.31f9785363b2ap+3',
            '0x1.2b8f8e1f9d033p+3',
            '0x1.31d8ebc7648cdp+2',
            '0x1.9778a1b2fe4b7p+2',
            '0x1.978662c7866b4p+0',
            '0x1.9ed738992fdb6p+1',
            '0x0.0p+0',
        ]),
    ],
}


def test_flag_off_is_bit_identical_to_golden():
    """The frozen precision-blend path must be untouched, to the last bit."""
    for name, params, kwargs in _golden_cases():
        assert not params.use_hit_miss_mixture, f"{name} must exercise the frozen path"
        expected = GOLDEN[name]
        actual = _evaluate_case(params, kwargs)
        assert len(actual) == len(expected)
        for idx, ((val, grad), (exp_val, exp_grad)) in enumerate(zip(actual, expected)):
            assert val == float.fromhex(exp_val), f"{name}[{idx}] objective drifted"
            assert len(grad) == len(exp_grad)
            for j, (g, exp_g) in enumerate(zip(grad, exp_grad)):
                assert g == float.fromhex(exp_g), f"{name}[{idx}] grad[{j}] drifted"


def test_mixture_flag_defaults_off():
    assert cefe.CasadiEfeParams.__dataclass_fields__["use_hit_miss_mixture"].default is False
    assert _params().use_hit_miss_mixture is False


def test_flag_on_changes_the_objective():
    """Sanity: the flag actually routes somewhere else (guards a dead flag)."""
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    off = _evaluate_case(_params(), kwargs)
    on = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    assert any(a[0] != b[0] for a, b in zip(off, on))


def test_flag_on_never_reads_R_miss():
    """The mixture path must not depend on the unreconciled miss endpoint.

    ``MissEndpointPolicy`` blocks quoting 40 px vs 120 px; under the mixture the
    miss branch takes no update at all, so the constant must be irrelevant.
    """
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    a = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    b = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_miss=np.diag([40.0 ** 2, 40.0 ** 2])),
        kwargs,
    )
    for (va, ga), (vb, gb) in zip(a, b):
        assert va == vb
        assert ga == gb


# --------------------------------------------------------------------------
# Mixture semantics, exercised on the numeric helper directly
# --------------------------------------------------------------------------

_S_PRIOR = np.array(
    [
        [0.090, 0.020, 0.003],
        [0.020, 0.140, -0.006],
        [0.003, -0.006, 0.030],
    ]
)
_JAC = np.array([[420.0, -60.0, 0.0], [35.0, 380.0, 0.0]])
_R_COND = np.diag([2.5 ** 2, 2.5 ** 2])


def _mix_cov(p_use, S=_S_PRIOR, J=_JAC, R_cond=_R_COND):
    """Numeric evaluation of the symbolic mixture, via CasADi DM."""
    out = cefe.expected_posterior_cov_ca(
        ca.DM(np.asarray(S, dtype=float)),
        ca.DM(np.asarray(J, dtype=float)),
        ca.DM(np.asarray(R_cond, dtype=float)),
        ca.DM(float(p_use)),
    )
    return np.asarray(ca.DM(out))


def _hit_cov_numpy(S=_S_PRIOR, J=_JAC, R_cond=_R_COND):
    """Independent numpy reference for the hit branch (plain Schur form)."""
    S = np.asarray(S, dtype=float)
    J = np.asarray(J, dtype=float)
    Sigma = J @ S @ J.T + np.asarray(R_cond, dtype=float)
    K = S @ J.T @ np.linalg.inv(Sigma)
    return S - K @ (J @ S)


def test_mixture_at_p0_is_the_no_update_case():
    """p_use = 0: no measurement ever arrives, so the posterior IS the prior.

    Exactly the prior, not "the prior plus a regularisation floor": the Joseph
    construction needs no state-space floor, so the no-update branch is clean.
    """
    got = _mix_cov(0.0)
    assert np.allclose(got, _S_PRIOR, atol=1e-15, rtol=0.0)


def test_mixture_at_p1_is_the_full_update_case():
    """p_use = 1: the full Kalman update with R_cond, and nothing else."""
    got = _mix_cov(1.0)
    assert np.allclose(got, _hit_cov_numpy(), atol=1e-12, rtol=0.0)


def test_mixture_is_convex_combination_of_the_two_branches():
    hit = _mix_cov(1.0)
    for p in (0.0, 0.15, 0.37, 0.5, 0.82, 1.0):
        expected = p * hit + (1.0 - p) * _S_PRIOR
        assert np.allclose(_mix_cov(p), expected, atol=1e-14, rtol=0.0)


def test_mixture_trace_is_monotone_decreasing_in_p_use():
    ps = np.linspace(0.0, 1.0, 41)
    traces = [float(np.trace(_mix_cov(p))) for p in ps]
    diffs = np.diff(traces)
    assert np.all(diffs <= 1e-12), "more availability must never increase uncertainty"
    assert traces[0] > traces[-1]


def test_mixture_is_psd_throughout():
    for p in np.linspace(0.0, 1.0, 51):
        P = _mix_cov(p)
        assert np.allclose(P, P.T, atol=1e-12)
        eig = np.linalg.eigvalsh(0.5 * (P + P.T))
        assert eig.min() > 0.0, f"non-PD posterior at p_use={p}: min eig {eig.min():.3e}"


def test_mixture_psd_for_hard_priors():
    """Near-singular and strongly correlated priors must still yield a PD mixture."""
    hard = [
        np.diag([1e-6, 1e-6, 1e-6]),
        np.array([[0.5, 0.4999, 0.0], [0.4999, 0.5, 0.0], [0.0, 0.0, 1e-5]]),
        np.array([[2.0, 0.0, 1.4], [0.0, 2.0, 0.0], [1.4, 0.0, 1.0]]),
    ]
    for S in hard:
        for p in (0.0, 0.25, 0.5, 0.75, 1.0):
            P = _mix_cov(p, S=S)
            eig = np.linalg.eigvalsh(0.5 * (P + P.T))
            assert eig.min() > 0.0


def test_mixture_never_exceeds_the_prior_in_loewner_order():
    for p in np.linspace(0.0, 1.0, 21):
        delta = _S_PRIOR - _mix_cov(p)
        eig = np.linalg.eigvalsh(0.5 * (delta + delta.T))
        assert eig.min() >= -1e-9, "a measurement must never inflate the belief"


def test_expected_uncertainty_matches_branch_weighted_entropy():
    """The epistemic scalar is E[H], i.e. H(prior) - p_use * mutual information."""

    def ent(P):
        n = P.shape[0]
        return 0.5 * (n * math.log(2.0 * math.pi * math.e) + math.log(np.linalg.det(P)))

    h_prior = ent(_S_PRIOR)
    h_hit = ent(_hit_cov_numpy())
    for p in (0.0, 0.3, 0.61, 1.0):
        got = float(
            ca.DM(
                cefe.expected_posterior_uncertainty_ca(
                    ca.DM(_S_PRIOR), ca.DM(_JAC), ca.DM(_R_COND), ca.DM(float(p))
                )
            )
        )
        assert got == pytest.approx(p * h_hit + (1.0 - p) * h_prior, rel=1e-9, abs=1e-9)

    # information gain is non-negative, so the scalar is monotone decreasing
    assert h_hit <= h_prior


def test_expected_uncertainty_is_monotone_decreasing_in_p_use():
    vals = [
        float(
            ca.DM(
                cefe.expected_posterior_uncertainty_ca(
                    ca.DM(_S_PRIOR), ca.DM(_JAC), ca.DM(_R_COND), ca.DM(float(p))
                )
            )
        )
        for p in np.linspace(0.0, 1.0, 41)
    ]
    assert np.all(np.diff(vals) <= 1e-12)
    assert vals[0] > vals[-1]


def test_mixture_objective_is_differentiable_and_finite():
    """The whole point of staying symbolic: the NLP still gets a usable gradient."""
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params, _camera_H(), approx="ET1", p_vis_state=_p_vis_fixture()
    )
    for u, m0, S0, goal_obs, goal_xy, prog in _EVAL_POINTS:
        val, grad = valgrad(
            np.asarray(u, dtype=float),
            np.asarray(m0, dtype=float),
            np.asarray(S0, dtype=float),
            np.asarray(goal_obs, dtype=float),
            np.asarray(goal_xy, dtype=float),
            float(prog),
        )
        assert math.isfinite(val)
        assert np.all(np.isfinite(grad))
        assert np.any(np.abs(grad) > 0.0)


def test_mixture_gradient_matches_finite_differences():
    """No symbolic branch sneaked in: autodiff agrees with central differences."""
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params, _camera_H(), approx="ET1", p_vis_state=_p_vis_fixture()
    )
    u, m0, S0, goal_obs, goal_xy, prog = _EVAL_POINTS[0]
    u = np.asarray(u, dtype=float)
    args = (
        np.asarray(m0, dtype=float),
        np.asarray(S0, dtype=float),
        np.asarray(goal_obs, dtype=float),
        np.asarray(goal_xy, dtype=float),
        float(prog),
    )
    _, grad = valgrad(u, *args)
    h = 1e-6
    for i in range(u.size):
        up = u.copy()
        um = u.copy()
        up[i] += h
        um[i] -= h
        fd = (valgrad(up, *args)[0] - valgrad(um, *args)[0]) / (2.0 * h)
        assert fd == pytest.approx(grad[i], rel=2e-4, abs=2e-5)


def test_mixture_r_cond_defaults_to_r_visible_and_is_overridable():
    """R_cond default is documented as params.R_visible until a field is measured."""
    kwargs = dict(approx="ET1", p_vis_state=_p_vis_fixture())
    implicit = _evaluate_case(_params(use_hit_miss_mixture=True), kwargs)
    explicit = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_cond=np.diag([2.5 ** 2, 2.5 ** 2])),
        kwargs,
    )
    for (va, ga), (vb, gb) in zip(implicit, explicit):
        assert va == vb
        assert ga == gb

    other = _evaluate_case(
        _params(use_hit_miss_mixture=True, R_cond=np.diag([9.0 ** 2, 6.0 ** 2])),
        kwargs,
    )
    assert any(a[0] != b[0] for a, b in zip(implicit, other))


def test_mixture_accepts_state_dependent_r_cond_and_bias():
    """Plumbing for a measured, spatially-varying R_cond(x) and bias b(x).

    Values here are placeholders: no field has been measured yet, so nothing is
    wired on by default. This only proves the hooks are symbolic and usable.
    """
    s = ca.MX.sym("s", 3)
    r_cond_state = ca.Function(
        "r_cond_fixture",
        [s],
        [ca.diag(ca.vertcat(4.0 + 0.5 * s[0] ** 2, 4.0 + 0.5 * s[1] ** 2))],
        ["state"],
        ["R"],
    )
    bias_state = ca.Function(
        "bias_fixture", [s], [ca.vertcat(0.3 * s[0], -0.2 * s[1])], ["state"], ["b"]
    )
    params = _params(use_hit_miss_mixture=True)
    valgrad = cefe.make_efe_valgrad_fn(
        params,
        _camera_H(),
        approx="ET1",
        p_vis_state=_p_vis_fixture(),
        R_cond_state=r_cond_state,
        obs_bias_state=bias_state,
    )
    u, m0, S0, goal_obs, goal_xy, prog = _EVAL_POINTS[0]
    val, grad = valgrad(
        np.asarray(u, dtype=float),
        np.asarray(m0, dtype=float),
        np.asarray(S0, dtype=float),
        np.asarray(goal_obs, dtype=float),
        np.asarray(goal_xy, dtype=float),
        float(prog),
    )
    assert math.isfinite(val)
    assert np.all(np.isfinite(grad))


def test_state_dependent_hooks_rejected_when_flag_off():
    """Guard: the frozen path must never silently accept mixture-only inputs."""
    with pytest.raises(RuntimeError, match="use_hit_miss_mixture"):
        cefe.make_efe_valgrad_fn(
            _params(),
            _camera_H(),
            approx="ET1",
            R_cond_state=_p_vis_fixture(),
        )
