"""No tracked file may read from a path that only exists on one machine.

A deck figure once read its input from `/tmp/.../<session-id>/scratchpad/camdensity.json`
-- a previous session's scratch directory. The figure could not be regenerated by anyone,
including on the machine that made it, because the directory is deleted between sessions.
It went unnoticed because the path is not a word like TODO or HANDOFF; it looks like code.

An absolute path into /tmp, a home directory, or a session scratchpad means the artifact
is not reproducible from the repository, which is the one property every input to a result
has to have. Write outputs under `logs/`, read inputs from `logs/` or the repo, and locate
the root with `figures/paths.py: repo_root()`.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]

#: Directories whose contents are tracked or are the reproducible surface of the project.
SEARCH_DIRS = ("src", "scripts", "experiments", "tests", "config", "schemas")

# These experiment trees contain immutable run/audit records. Their JSON path
# values describe where a recorded run happened; they are not opened as current
# dependencies. Executable files in the same trees remain in the scan.
RECORDED_EVIDENCE_JSON_ROOTS = (
    ("experiments", "runtime_integrity"),
    ("experiments", "estimator_consistency"),
)
RECORDED_EVIDENCE_FILES = (
    ("experiments", "camera_observation_characterization", "icra_p1_geometry_poses.json"),
    ("experiments", "camera_observation_characterization", "icra_p1b_geometry_poses.json"),
)

#: An absolute path that cannot exist on another machine.
MACHINE_LOCAL = re.compile(
    r"""["'](?:
          /tmp/            # scratch, deleted between sessions
        | /var/tmp/
        | /home/[A-Za-z0-9_.-]+/   # somebody's home directory
        | /Users/[A-Za-z0-9_.-]+/
    )[^"']*["']""",
    re.VERBOSE,
)

#: Legitimate uses: the tempfile module makes its own paths at runtime, and pytest's
#: tmp_path fixture is the sanctioned way for a test to need a scratch directory.
ALLOWED_LINE = re.compile(r"tempfile|TemporaryDirectory|tmp_path|mkdtemp|gettempdir")

# These literals select disposable OUTPUT locations. They are not input
# dependencies and the owning library/runner creates their contents.
ALLOWED_OUTPUT_LINE = re.compile(
    r"os\.environ\.setdefault\(\s*['\"](?:MPLCONFIGDIR|YOLO_CONFIG_DIR)['\"]"
    r"\s*,\s*['\"]/(?:var/)?tmp/"
    r"|_build_launch_cmd\([^\n]*Path\(['\"]/(?:var/)?tmp/"
)

#: A file that CREATES its own scratch directory and cleans it up is doing ordinary
#: staging, not depending on somebody else's leftovers. The failure this test exists for
#: is reading a path that had to be produced by a different process, on a different day.
#: A home directory is never acceptable either way -- it names one machine's user.
CREATES_OWN_SCRATCH = re.compile(r"mkdir -p /(?:var/)?tmp/|-o /(?:var/)?tmp/|-d /(?:var/)?tmp/")
HOME_PATH = re.compile(r"[\"'](?:/home/|/Users/)[A-Za-z0-9_.-]+/")


def _is_recorded_evidence(path: Path, *, repo: Path = REPO) -> bool:
    """Identify passive records without exempting executable project source."""
    relative = path.relative_to(repo)
    in_audit_evidence_root = any(
        relative.parts[:len(root)] == root
        for root in RECORDED_EVIDENCE_JSON_ROOTS
    )
    if in_audit_evidence_root and (
        "source_snapshot" in relative.parts or "source_snapshots" in relative.parts
    ):
        return True
    return path.suffix == ".json" and (
        in_audit_evidence_root or relative.parts in RECORDED_EVIDENCE_FILES
    )


def _candidate_paths(*, repo: Path = REPO) -> list[Path]:
    """Return tracked and newly authored, non-ignored project files."""
    result = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "--", *SEARCH_DIRS],
        cwd=repo,
        check=True,
        capture_output=True,
        text=True,
    )
    return [repo / line for line in result.stdout.splitlines() if line]


def _offending_lines(path: Path, *, repo: Path = REPO) -> list[str]:
    text = path.read_text(errors="replace")
    self_managed_scratch = bool(CREATES_OWN_SCRATCH.search(text))
    hits = []
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if ALLOWED_LINE.search(stripped) or ALLOWED_OUTPUT_LINE.search(stripped):
            continue
        match = MACHINE_LOCAL.search(stripped)
        if not match:
            continue
        # a home directory pins the artifact to one user's machine, always
        if not HOME_PATH.search(stripped) and self_managed_scratch:
            continue
        hits.append(f"{path.relative_to(repo)}:{number}: {stripped[:100]}")
    return hits


def test_no_tracked_source_reads_a_machine_local_path():
    offenders: list[str] = []
    for path in _candidate_paths():
        if path.suffix not in (".py", ".yaml", ".yml", ".json", ".sh"):
            continue
        if path.name == Path(__file__).name or _is_recorded_evidence(path):
            continue
        offenders.extend(_offending_lines(path))
    assert not offenders, (
        "these read or write a path that exists only on one machine, so the artifact "
        "they produce cannot be reproduced from the repository:\n  "
        + "\n  ".join(offenders)
    )


def test_guard_still_catches_a_machine_local_input(tmp_path):
    source = tmp_path / "reader.py"
    source.write_text(
        "from pathlib import Path\n"
        "payload = Path('/tmp/old-session/input.json').read_text()\n"
    )
    assert _offending_lines(source, repo=tmp_path)


def test_guard_allows_a_declared_disposable_output_cache(tmp_path):
    source = tmp_path / "cache.py"
    source.write_text(
        "import os\n"
        "os.environ.setdefault('MPLCONFIGDIR', '/tmp/project_plot_cache')\n"
    )
    assert _offending_lines(source, repo=tmp_path) == []


def test_named_output_cache_in_a_home_directory_is_still_rejected(tmp_path):
    source = tmp_path / "cache.py"
    source.write_text(
        "import os\n"
        "os.environ.setdefault('MPLCONFIGDIR', '/home/alice/project_plot_cache')\n"
    )
    assert _offending_lines(source, repo=tmp_path)


def test_recorded_result_is_distinct_from_active_config(tmp_path):
    evidence = tmp_path / "experiments" / "runtime_integrity" / "audit" / "record.json"
    config = tmp_path / "config" / "results.json"
    evidence.parent.mkdir(parents=True)
    config.parent.mkdir(parents=True)
    payload = '{"input_path": "/home/alice/stale/input.csv"}'
    evidence.write_text(payload)
    config.write_text(payload)

    assert _is_recorded_evidence(evidence, repo=tmp_path)
    assert not _is_recorded_evidence(config, repo=tmp_path)
    assert _offending_lines(config, repo=tmp_path)


def test_new_untracked_source_remains_in_the_guard_surface(tmp_path):
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    source = tmp_path / "src" / "new_reader.py"
    source.parent.mkdir()
    source.write_text("Path('/tmp/stale/input.csv').read_text()\n")
    assert source in _candidate_paths(repo=tmp_path)
    assert _offending_lines(source, repo=tmp_path)


def test_frozen_source_snapshot_is_not_reclassified_as_live_source(tmp_path):
    snapshot = tmp_path / "experiments" / "runtime_integrity" / "audit" / "source_snapshot" / "old.py"
    snapshot.parent.mkdir(parents=True)
    snapshot.write_text("Path('/home/alice/old/input.csv').read_text()\n")
    assert _is_recorded_evidence(snapshot, repo=tmp_path)


def test_source_snapshot_name_outside_evidence_root_has_no_exemption(tmp_path):
    source = tmp_path / "src" / "source_snapshot" / "reader.py"
    source.parent.mkdir(parents=True)
    source.write_text("Path('/home/alice/input.csv').read_text()\n")
    assert not _is_recorded_evidence(source, repo=tmp_path)
    assert _offending_lines(source, repo=tmp_path)


def test_future_camera_characterization_config_is_not_passive_evidence(tmp_path):
    config = (
        tmp_path / "experiments" / "camera_observation_characterization"
        / "method_config.json"
    )
    config.parent.mkdir(parents=True)
    config.write_text('{"input_path": "/home/alice/input.csv"}')
    assert not _is_recorded_evidence(config, repo=tmp_path)
    assert _offending_lines(config, repo=tmp_path)
